server.port=8888
# Database
db.url=${DB_URL}
db.user=${DB_USER}
db.pass=${DB_PASS}
db.driver=${DB_DRIVER}
# JWT config
app.jwtCookieName=${JWT_COOKIE_NAME}
app.jwtRefreshCookieName=${JWT_COOKIE_REFRESH_NAME}
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationsMs=${JWT_EXPIRATION}
app.jwtRefreshExpirationsMs=${JWT_REFRESH_EXPIRATION}
setup.admin.username=${ADMIN_USERNAME}
setup.admin.password=${ADMIN_PASSWORD}
# Flyway
flyway.locations=classpath:db/migration
#Config Cloudinary
cloudinary.folderName=${CLOUDINARY_FOLDER_NAME}
cloudinary.cloudName=${CLOUDINARY_CLOUD_NAME}
cloudinary.apiKey=${CLOUDINARY_API_KEY}
cloudinary.apiSecret=${CLOUDINARY_API_SECRET}
