-- V5: Add warehouse + inventory tables and align product_items columns.
-- This migration is idempotent: it only creates tables/columns if they
-- don't already exist, so it is safe even on fresh DBs that already
-- include the same definitions in V1.

-- ── Warehouses ─────────────────────────────────────────────────────────────
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'WAREHOUSES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE warehouses (
                id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
                name       VARCHAR2(100) NOT NULL,
                address    VARCHAR2(500),
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT pk_warehouses PRIMARY KEY (id)
            )
        ]';
    END IF;
END;
/

-- ── Warehouse locations ────────────────────────────────────────────────────
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'WAREHOUSE_LOCATIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE warehouse_locations (
                id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
                warehouse_id NUMBER(19, 0) NOT NULL,
                zone_name    VARCHAR2(50),
                row_num      VARCHAR2(20),
                shelf_num    VARCHAR2(20),
                bin_num      VARCHAR2(20),
                CONSTRAINT pk_warehouse_locations PRIMARY KEY (id),
                CONSTRAINT fk_loc_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
                CONSTRAINT uk_location_coords UNIQUE (warehouse_id, zone_name, row_num, shelf_num, bin_num)
            )
        ]';
    END IF;
END;
/

-- ── Align product_items: add location_id + supplier_id, drop supplier_name ──
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_columns
     WHERE table_name = 'PRODUCT_ITEMS' AND column_name = 'LOCATION_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE product_items ADD (location_id NUMBER(19, 0))';
        EXECUTE IMMEDIATE
            'ALTER TABLE product_items ADD CONSTRAINT fk_items_location ' ||
            'FOREIGN KEY (location_id) REFERENCES warehouse_locations (id)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_columns
     WHERE table_name = 'PRODUCT_ITEMS' AND column_name = 'SUPPLIER_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE product_items ADD (supplier_id NUMBER(19, 0))';
        EXECUTE IMMEDIATE
            'ALTER TABLE product_items ADD CONSTRAINT fk_items_supplier ' ||
            'FOREIGN KEY (supplier_id) REFERENCES suppliers (id)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_columns
     WHERE table_name = 'PRODUCT_ITEMS' AND column_name = 'SUPPLIER_NAME';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE product_items DROP COLUMN supplier_name';
    END IF;
END;
/

-- ── Inventory sessions ─────────────────────────────────────────────────────
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'INVENTORY_SESSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE inventory_sessions (
                id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
                created_by NUMBER(19, 0) NOT NULL,
                status     VARCHAR2(20) DEFAULT 'IN_PROGRESS',
                start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                end_date   TIMESTAMP,
                CONSTRAINT pk_inventory_sessions PRIMARY KEY (id),
                CONSTRAINT fk_inventory_user FOREIGN KEY (created_by) REFERENCES users (id),
                CONSTRAINT ck_inventory_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
            )
        ]';
    END IF;
END;
/

-- ── Inventory details ──────────────────────────────────────────────────────
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'INVENTORY_DETAILS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE inventory_details (
                id            NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
                session_id    NUMBER(19, 0),
                imei          VARCHAR2(50),
                expected_loc  NUMBER(19, 0),
                actual_loc    NUMBER(19, 0),
                record_status VARCHAR2(20),
                note          VARCHAR2(255),
                CONSTRAINT pk_inventory_details PRIMARY KEY (id),
                CONSTRAINT fk_inv_det_session FOREIGN KEY (session_id) REFERENCES inventory_sessions (id),
                CONSTRAINT fk_inv_det_expected FOREIGN KEY (expected_loc) REFERENCES warehouse_locations (id),
                CONSTRAINT fk_inv_det_actual FOREIGN KEY (actual_loc) REFERENCES warehouse_locations (id),
                CONSTRAINT ck_record_status CHECK (record_status IN ('MATCH', 'MISMATCH', 'MISSING', 'EXTRA'))
            )
        ]';
    END IF;
END;
/
